title: Radhika Mishra
logo: /assets/img/logo.png
description: Hi, I'm Radhika Mishra, a data scientist with a background in applied physics. I hold a master's degree in applied physics and bring over a year of professional experience in the field. Currently, I am working at Fresko Innovation Labs, leveraging my skills in data science to solve complex problems and drive impactful insights..
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
